#pragma once
#include <sstream>
#include <iomanip>
#include <string>
#include <vector>
#include <cstdarg>
#include <memory>
#include <iostream>
#include <thread>
#include <chrono>
#include <algorithm>
#include "database.h"
#include "manager.h"
#include "user.h"
#include "crypt.h"
#include "error.h"
#include "movie.h"
#include "show.h"