#pragma once
#include <string>
#include <fstream>
#include <algorithm>
#include <iostream>
#include "core\models\user.h"
#include "core\models\movie.h"
#include "core\models\show.h"
#include "core\utils.h"
#include "core\error.h"